on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: node -v
      - env:
          GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        run: printenv
