name: Push Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: GITHUB_PULL_REQUEST_NUMBER=$(sed -E -e 's_refs/pull/([0-9]*)/merge_\1_' <<< $GITHUB_REF)
      - run: printenv
