on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - env:
          GITHUB_PR_NUMBER: ${{ github.event.number }}
        run: npm run scan:pull
